import {createRefreshController} from './refresh.js';
import {createModel,escapeHTML as e,formatNumber as num,formatRate as pct,formatSeconds as secs,NODE_NAMES,DEVICES,BROWSERS,SOURCES} from './data.js';
import {trendChart,compareBars} from './charts.js';
import {renderBreakpointMap,COUNTRY_NAMES,dimensionLabel} from './breakpoints.js';
import {renderStrategy} from './strategy.js';
import {renderDeepDiagnosis,renderDeepRetention,renderDeepCommercial} from './deep_panels.js';
import {renderDiagnosis,renderRetention,renderCommercial,renderOpportunities} from './insights.js';
const $=s=>document.querySelector(s);
const CONFIG=window.MEIGEN_CONFIG||{mode:'live',reportUrl:'/api/report'};
const ICONS={overview:'M3 3h6v6H3zM13 3h6v6h-6zM3 13h6v6H3zM13 13h6v6h-6z',demand:'M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6M2 19v-3a6 6 0 0 1 12 0v3M16 3a3 3 0 0 1 0 6M17 12a5 5 0 0 1 3 4v3',journey:'M3 5h5v5H3zM14 13h5v5h-5zM8 7h7v6M5 10v6h9',traffic:'M3 19V4M3 19h16M7 16V9M12 16V5M17 16v-5',diagnosis:'M4 5h5v5H4zM13 3h5v5h-5zM13 14h5v5h-5zM9 7h2V5h2M9 8h2v8h2',retention:'M18 8a7 7 0 1 0 0 7M18 3v5h-5M10 7v5l3 2',commercial:'M3 6h16v12H3zM3 9h16M6 14h3',opportunities:'M11 2a6 6 0 0 0-4 10v3h8v-3a6 6 0 0 0-4-10M8 18h6M9 21h4'};
const VIEWS={overview:['概览','MeiGen 入口分析'],demand:['需求画像','需求与用户画像','识别进入网站的任务，查看每种需求走到了哪里。'],journey:['用户流程','用户使用流程','点击节点，查看推进、退出和其他去向。'],traffic:['流量变化','流量变化与运营线索','找到放量时点，并判断新增流量有没有走向有效使用。'],diagnosis:['分岔诊断','为什么有人继续，有人停止','在同一种需求里，比较关键节点前后的体验。'],retention:['回访与复用','从一次体验到再次使用','区分再次访问与再次使用，寻找值得强化的首次体验。'],commercial:['使用到付费','使用怎样走向付费','从结果预览、下载意图，到价格、结账与最终价值。'],opportunities:['优化行动','优化行动与验证','先修复任务连续性，再放大有价值的体验和流量。']};
const state={view:location.hash.slice(1)||'overview',filters:{demand:'all',maturity:'all',device:'all',browser:'all',source:'all',entry:'all',country:'all',language:'all',start:null,end:null},node:'use',metric:'visits',matrixMode:'visit',dailyMode:'stages',journeyTab:'map',breakpointDimension:'demand',breakpointExpanded:false,deepBranch:'immediate',deepDays:7,deepMinutes:5,analysisTabs:{diagnosis:'deep',retention:'deep',commercial:'deep'},report:null,model:null,status:null,selectedDate:null,loading:false,auto:false};
let toastTimer;
const refreshController=createRefreshController({getReport:()=>state.report,onReportChange:()=>loadReport(),toast,snapshot:CONFIG.mode==='snapshot'});
const icon=k=>`<svg viewBox="0 0 22 22" aria-hidden="true"><path d="${ICONS[k]}"/></svg>`;
const scope=t=>`<span class="scope-tag">${e(t)}</span>`;
const filtered=()=>Object.entries(state.filters).some(([k,v])=>v&&v!=='all');
const allScope=()=>`${state.filters.demand==='all'?'全部需求':state.model.names[state.filters.demand]} · ${state.filters.device==='all'?'全部设备':DEVICES[state.filters.device]||state.filters.device}`;
const empty=(title='当前筛选没有访问记录',text='调整需求、行为状态或日期后再查看。')=>`<div class="empty"><h3>${e(title)}</h3><p>${e(text)}</p><button class="button" data-action="reset">清除筛选</button></div>`;
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3200);}
function renderNav(){const groups=[['总览',['overview','demand','traffic']],['行为',['journey','diagnosis','retention','commercial']],['增长',['opportunities']]];$('#nav').innerHTML=groups.map(([g,vs])=>`<div class="nav-label">${g}</div>${vs.map(v=>`<a class="nav-link ${v===state.view?'active':''}" href="#${v}" ${v===state.view?'aria-current="page"':''}>${icon(v)}<span>${VIEWS[v][0]}</span></a>`).join('')}`).join('');}
function navigate(view){if(!VIEWS[view])view='overview';state.view=view;history.replaceState(null,'','#'+view);closeNav();render();window.scrollTo({top:0,behavior:'instant'});}
function closeNav(){$('#sidebar').classList.remove('open');$('#navScrim').hidden=true;}
function setOptions(sel,dict,title){const el=$(sel),value=el.value;el.innerHTML=`<option value="all">${title}</option>`+Object.entries(dict).map(([k,v])=>`<option value="${e(k)}">${e(v)}</option>`).join('');if([...el.options].some(o=>o.value===value))el.value=value;}
function initFilters(){const m=state.model;setOptions('#demandSelect',m.names,'全部需求');setOptions('#maturitySelect',m.stages,'全部状态');setOptions('#deviceSelect',Object.fromEntries(m.dictionaries.device.map(x=>[x,DEVICES[x]||x])),'全部设备');setOptions('#browserSelect',Object.fromEntries(m.dictionaries.browser.map(x=>[x,BROWSERS[x]||x])),'全部浏览器');setOptions('#sourceSelect',SOURCES,'全部 MeiGen 标记');setOptions('#entrySelect',Object.fromEntries((m.dictionaries.entry||[]).map(x=>[x,x])),'全部入口');setOptions('#countrySelect',Object.fromEntries((m.dictionaries.country||[]).map(x=>[x,COUNTRY_NAMES[x]||x])),'全部地区');setOptions('#languageSelect',Object.fromEntries((m.dictionaries.language||[]).map(x=>[x,x])),'全部语言');syncFilters();}
function syncFilters(){if(!state.model)return;const f=state.filters;for(const [k,id] of Object.entries({demand:'demandSelect',maturity:'maturitySelect',device:'deviceSelect',browser:'browserSelect',source:'sourceSelect',entry:'entrySelect',country:'countrySelect',language:'languageSelect'}))$('#'+id).value=f[k];
 const labels={demand:state.model.names,maturity:state.model.stages,device:DEVICES,browser:BROWSERS,source:SOURCES,entry:{},country:COUNTRY_NAMES,language:{}};const chips=Object.entries(labels).filter(([k])=>f[k]!=='all').map(([k,d])=>`<button class="filter-chip" data-clear="${k}" title="移除此筛选">${e(d[f[k]]||f[k])} ×</button>`);if(f.start)chips.push(`<button class="filter-chip" data-clear="date">${f.start.slice(5)} — ${f.end.slice(5)} ×</button>`);$('#filterChips').innerHTML=chips.join('');$('#filterCount').textContent=chips.length;$('#filterCount').hidden=!chips.length;$('#resetFilters').hidden=!chips.length;$('#startDate').value=f.start||state.report.window.start.slice(0,10);$('#endDate').value=f.end||cutoffDate();}
function cutoffDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(state.report.window.end));}
function resetFilters(){state.filters={demand:'all',maturity:'all',device:'all',browser:'all',source:'all',entry:'all',country:'all',language:'all',start:null,end:null};state.selectedDate=null;$('#dateSelect').value='all';$('#datePanel').hidden=true;syncFilters();render();}
function kpis(){const s=state.model.summary(state.filters);return `<div class="kpi-grid">${[
 ['入口访问',num(s.visits),`访问 · ${allScope()}`,'完整访问的首个页面带有MeiGen引荐或UTM标记'],
 ['注册后使用',num(s.registered_use),`${pct(s.registered_use_rate)} 的合格访问`,'出现注册信号之后再提交任务；不是实际下载完成'],
 ['尝试使用',num(s.used),`${pct(s.used_rate)} 的合格访问`,'send_message任务提交信号；不同工具的完成需另行记录'],
 ['重复使用',num(s.reused),`${s.used?pct(s.reused/s.used):'—'} 的使用访问`,'同次访问在更晚时间再次提交；跨访问复用见回访模块'],
 ['主动付费意图',num(s.payment_intent),`${num(s.checkout)} 次访问进入结账`,'明确权益/套餐操作或发起结账，付费界面曝光不计入']
 ].map(([label,value,caption,tip])=>`<div class="card kpi"><div class="kpi-label">${label}<span class="info-icon" title="${e(tip)}">i</span></div><div class="kpi-value">${value}</div><div class="kpi-caption">${e(caption)}</div></div>`).join('')}</div>`;}
function trendPanel(height=245){const days=state.model.daily(state.filters).map(d=>({...d,unavailable:state.metric!=='visits'&&!d.behavior_observed}));const labels={visits:'入口访问',registered_use:'注册后使用',payment_intent:'主动付费意图'};const chosen=days.find(d=>d.date===state.selectedDate);return `<article class="card"><div class="card-head"><div><h2>流量与有效使用</h2><p>日趋势 · 点击日期查看人数，进一步定位当日旅程</p></div><div class="tabs" aria-label="趋势指标">${Object.entries(labels).map(([k,l])=>`<button data-metric="${k}" class="${state.metric===k?'active':''}">${l}</button>`).join('')}</div></div><div class="trend-body">${trendChart(days,{metric:state.metric,label:labels[state.metric],height,selectedDate:state.selectedDate,maxLabels:window.innerWidth<580?5:8})}</div>${chosen?`<div class="trend-selected"><span><strong>${chosen.date}</strong> · 入口 ${num(chosen.visits)} · 注册后使用 ${chosen.behavior_observed?num(chosen.registered_use):'尚无完整记录'}</span><button class="text-button blue" data-filter-date="${chosen.date}">查看当日流程 →</button></div>`:`<div class="chart-caption"><span class="legend-dot"></span><span>首末日为部分数据；8/17前仅有页面记录。</span><button data-view="traffic">查看流量变化 →</button></div>`}</article>`;}
function demandBars(limit=6){const rows=state.model.breakdown(state.filters,'demand').slice(0,limit);const max=Math.max(...rows.map(x=>x.visits),1);return rows.length?`<div class="bar-list">${rows.map(x=>`<div class="bar-item"><button data-select-demand="${e(x.key)}">${e(state.model.names[x.key]||x.key)}</button><div class="bar-track"><div class="bar-fill" style="width:${x.visits/max*100}%"></div></div><span class="bar-number">${num(x.visits)}</span></div>`).join('')}</div>`:empty();}
function decisions(){return `<div class="decision-list">${[
 ['01','回查 9/10 的任务承接','同入口、同素材的后续路径出现变化，优先检查认证回跳与原任务恢复。','diagnosis'],
 ['02','复制有价值的第二次操作','图片修复围绕继续调整，视频围绕预览与导出权益，分别设计实验。','retention'],
 ['03','复盘 8/23 的有效放量','这一天流量和使用率同时提升，适合回查当时的曝光与运营操作。','traffic']
 ].map(([n,t,p,v])=>`<a href="#${v}" data-view="${v}" class="decision-row"><span class="decision-number">${n}</span><div class="decision-content"><h3>${t}</h3><p>${p}</p></div><span class="arrow-link">›</span></a>`).join('')}</div>`;}
const NODE_COPY={
 entry:['入口后的第一步','入口需求与页面承诺是否一致，是否能直接开始当前任务。','先优先处理图片修复与商品视频的移动端首屏；同一需求下比较卡片与入口。','demand'],
 landing:['落地承接','区分原工具内操作、进入工作台与认证回跳，找到需求在哪一步变成真实任务。','把首屏操作入口和内容区按钮的去向说明清楚，减少无关中间步骤。','diagnosis'],
 browse:['从探索到操作','查看案例、切换页面之后，有多少人开始注册或提交。页面访问本身不代表任务已开始。','用示例、默认素材和具体任务说明帮助用户开始，并保留已表达的需求。','diagnosis'],
 register:['注册后的原任务续接','顺畅的注册路线可以在几秒内继续提交；经过认证页的路线要额外检查素材、输入和返回位置。','认证后直接恢复原任务，避免让用户重新找入口或再次输入。','diagnosis'],
 use:['首次尝试之后发生了什么','再次提交是当前可见的操作深度。没有后续动作既可能是已完成，也可能是中断，需要结果与下载记录来区分。','图片修复测试结果对比与继续调整；视频重点测试预览和导出权益。','diagnosis'],
 reuse:['重复使用如何走向更高价值','同次重复使用与跨访问回访分开看。不同任务的重复操作与付费意图关系并不相同。','支持有价值的第二次操作，并用结果质量、下载及7日再次使用验证。','retention'],
 payment:['从结账到真正获得结果','价格、选择套餐、结账和付款分别统计。当前未发现可关联的purchase，不把结账当付款成功。','让结账返回原结果，并补齐下载完成、订阅和试用转付费的真实结果记录。','commercial']};
function flowPanel({compact=false}={}){const axes=state.model.axis(state.filters);const current=axes.find(x=>x.node===state.node)||axes[0];const C=[...NODE_COPY[current.node]];if(current.node==='payment'&&current.arrived>0)C[1]='当前可查看支付记录之后的继续操作。价格与结账分别统计，实际下载是最终价值目标。';const den=current.denominator;const left=den?current.continued/den*100:0,exit=den?current.exit/den*100:0,other=den?current.other/den*100:0;
 return `<article class="card" id="journeyCard"><div class="card-head"><div><h2>用户使用流程</h2><p>选择任一节点，查看这一步之后的行为</p></div><span class="scope-tag blue-tag">${e(allScope())}</span></div><div class="flow-axis"><div class="flow-track" aria-label="用户使用流程节点">${axes.map((x,i)=>`<button class="flow-node ${x.node===state.node?'active':''} ${!x.arrived?'node-zero':''}" data-node="${x.node}" aria-pressed="${x.node===state.node}"><span class="node-circle">${i+1}</span><span class="node-name">${NODE_NAMES[x.node]}</span><span class="node-value">${num(x.arrived)}</span><span class="node-mini">${x.node==='entry'?'已抵达站内':x.node==='payment'?'可关联支付记录':x.pending?`${num(x.pending)} 待观察`:'到达访问'}</span></button>${i<axes.length-1?'<span class="flow-connector" aria-hidden="true"><svg viewBox="0 0 34 14"><path d="M1 7H31M26 2l5 5-5 5"/></svg></span>':''}`).join('')}</div></div><div class="flow-note"><span>入口与落地共用站内观测起点，实际路径允许跳步或先用后注册。</span><span>复用＝同次再次提交<span class="flow-scroll-hint"> · 左右滑动查看全部步骤</span></span></div><div class="node-detail"><div class="node-detail-head"><div><h3>${NODE_NAMES[current.node]} <span class="muted">/</span> ${e(current.target_label.replace('（无外链点击数据）',''))}</h3><p>观察节点后的 30 分钟 · ${num(current.denominator)} 个完整起点${current.pending?` · ${num(current.pending)} 个待观察`:''}</p></div><button class="text-button" data-action="methods">指标口径 ⓘ</button></div>
 ${!den?`<div class="empty"><h3>${current.node==='payment'?'尚无可关联的支付记录':'当前人群尚未到达这个节点'}</h3><p>${current.node==='payment'?'可继续查看价格、套餐和结账路径。':'切换节点或调整筛选，查看已发生的行为。'}</p>${current.node==='payment'?'<button class="button" data-view="commercial">查看商业推进 →</button>':''}</div>`:`<div class="node-stats"><div class="node-stat"><span class="label">到达该节点</span><div class="value">${num(current.arrived)}</div><div class="caption">${num(den)} 个完整观察</div></div><div class="node-stat selected"><span class="label">下一步操作率</span><div class="value">${pct(current.continue_rate)}</div><div class="caption">${num(current.continued)} / ${num(den)}</div></div><div class="node-stat"><span class="label">退出率 <span class="info-icon" title="30分钟未见独立后续动作；不是确认离站或任务失败">i</span></span><div class="value">${pct(current.exit_rate)}</div><div class="caption">${num(current.exit)} 未见独立后续动作</div></div><div class="node-stat"><span class="label">推进耗时 · 中位数</span><div class="value">${secs(current.median_seconds_to_target)}</div><div class="caption">仅统计达到下一步的访问</div></div></div><div class="split-bar" aria-label="下一步${pct(current.continue_rate)}，退出${pct(current.exit_rate)}，其他${pct(den?current.other/den:null)}"><span style="width:${left}%;background:#6aa1f5"></span><span style="width:${other}%;background:#d6dce6"></span><span style="width:${exit}%;background:#edcccc"></span></div><div class="split-legend"><span><i class="legend-dot"></i>下一步 <b>${num(current.continued)}</b></span><span><i class="legend-dot gray"></i>其他有效去向 <b>${num(current.other)}</b></span><span><i class="legend-dot red"></i>未见后续动作 <b>${num(current.exit)}</b></span></div>`}
 <div class="node-insight"><div><h4>${C[0]}</h4><p>${C[1]}</p></div><div><h4>可以改变的体验</h4><p>${C[2]}</p><button class="action-link" data-view="${C[3]}">查看对应对照与行动 →</button></div></div></div></article>`;}
function overview(){return kpis()+`<div class="section-stack">${trendPanel(230)}<div class="grid-two"><article class="card"><div class="card-head"><h2>谁从 MeiGen 而来</h2><button class="text-button" data-view="demand">需求矩阵 →</button></div><div class="card-body">${demandBars()}</div></article><article class="card"><div class="card-head"><h2>现在最值得做的三件事</h2>${scope('已审分析')}</div><div class="card-body">${decisions()}</div></article></div>${flowPanel({compact:true})}</div>`;}
function matrixView(){const f={...state.filters,maturity:'all'};const rows=state.model.matrix(f);const stages=state.report.data.segments.maturity.stage_order;const account=state.matrixMode==='account';let useRows=rows;
 if(account){const groups=new Map();for(const r of state.report.data.accounts.matrix){if(state.filters.demand!=='all'&&r.entry_family!==state.filters.demand)continue;if(!groups.has(r.entry_family))groups.set(r.entry_family,{demand:r.entry_family,label:state.model.names[r.entry_family]||r.entry_family,total:r.row_n,counts:{}});groups.get(r.entry_family).counts[r.stage]=r.n;}useRows=[...groups.values()].sort((a,b)=>b.total-a.total);}
 const cols=account?['entry_only','browse','active_exploration','registered_no_observed_use','use_without_observed_signup','registered_use','repeat_use','payment_intent','payment_signal']:stages;
 const labels=account?{entry_only:'仅入口',browse:'浏览',active_exploration:'主动探索',registered_no_observed_use:'注册未使用',use_without_observed_signup:'使用',registered_use:'注册后使用',repeat_use:'跨访问复用',payment_intent:'付费意图',payment_signal:'支付'}:state.model.stages;
 const max=Math.max(...useRows.flatMap(r=>cols.map(s=>(r.counts[s]||0)/r.total)),.1);
 const table=useRows.length?`<div class="table-wrap"><table class="matrix-table"><thead><tr><th>入口需求</th>${cols.map(s=>`<th>${s==='registered_only'||s==='registered_no_observed_use'?'<span>有注册信号，</span><br><span>未见使用</span>':e(labels[s]||s)}</th>`).join('')}<th>合计</th></tr></thead><tbody>${useRows.map(r=>`<tr><td><button class="matrix-label" data-select-demand="${r.demand}">${e(r.label)}</button></td>${cols.map(s=>{const n=r.counts[s]||0;const intensity=n?Math.sqrt((n/r.total)/max):0;const bg=n?`rgba(59,130,246,${.06+intensity*.53})`:'#fafafa';return `<td><button class="matrix-cell ${!n?'zero':''} ${state.filters.maturity===s&&state.filters.demand===r.demand?'selected':''}" style="--cell-bg:${bg};--cell-fg:${intensity>.7?'#174b98':'#5273a0'}" ${account?`data-account-cell="${r.demand}"`:`data-cell-demand="${r.demand}" data-cell-stage="${s}"`} title="${e(r.label)} · ${e(labels[s])}：${num(n)}${account?'个账户':'次访问'}"><span>${n?num(n):'—'}</span>${n?`<small>${pct(n/r.total)}</small>`:''}</button></td>`;}).join('')}<td class="num">${num(r.total)}</td></tr>`).join('')}</tbody></table></div>`:empty();
 return kpis()+`<div class="section-stack"><article class="card"><div class="card-head"><div><h2>需求 × 行为成熟度</h2><p>${account?'可关联账户的累计状态，包含后续其他来源访问。':'每次访问归入最深可见状态；点击单元格，查看这类用户的流程。'}</p></div><div class="tabs"><button class="${!account?'active':''}" data-matrix-mode="visit">访问画像</button><button class="${account?'active':''}" data-matrix-mode="account">账户画像</button></div></div><div class="card-body">${table}<div class="matrix-caption"><span>${account?'账户视图仅按需求联动，使用完整历史观察窗。':'行内占比 · 每次访问只计入一个最深状态 · 未出现的结果完成不填成零'}</span><span class="heat-scale">少 ${[.08,.2,.34,.5,.65].map(a=>`<i style="background:rgba(59,130,246,${a})"></i>`).join('')} 多</span></div></div></article><div class="grid-two"><article class="card"><div class="card-head"><h2>需求规模</h2>${scope('按当前筛选')}</div><div class="card-body">${demandBars(10)}</div></article><article class="card"><div class="card-head"><h2>需求怎样转成任务</h2></div><div class="card-body"><div class="insight-box"><strong>从入口直接识别初始需求</strong><p>图片修复、商品视频、去水印等任务，按实际入口分类。后续进入工作台仍保留原任务，主动选择另一功能时再记录需求变化。</p></div><div class="decision-list">${['画像记录的是动态状态，用户可以在后续访问继续深入。','注册、使用与支付允许不同顺序，流程轴保留实际分支。','账户累计与单次访问分别统计，匿名访问仍进入主分析。'].map((x,i)=>`<div class="decision-row"><span class="decision-number">0${i+1}</span><div class="decision-content"><p>${x}</p></div></div>`).join('')}</div></div></article></div></div>`;}
function representativePanel(){
 const branch=({entry:'entry_continue',landing:'entry_continue',browse:'browse_use',register:'signup_use',use:'attempt_continue',reuse:'use_commercial'})[state.node];if(!branch)return '';
 const samples=state.report.data.branches.paths.representative_paths.filter(x=>x.branch===branch&&(state.filters.demand==='all'||x.demand===state.filters.demand));
 if(!samples.length)return '';
 const labels={login:'身份状态恢复',sign_up:'注册',guest_signup:'游客注册',send_message:'提交任务',paywall_shown:'展示权益提示',paywall_cta_click:'点击权益按钮',pricing_opened:'打开价格',view_item_list:'查看价格列表',plan_clicked:'选择套餐',begin_checkout:'发起结账',checkout_opened:'打开结账',onboarding_pick:'选择引导项',onboarding_shown:'显示引导',onboarding_dismiss:'关闭引导',offer_card_dismiss:'关闭优惠',guest_gate_shown:'展示注册门槛',ui_click:'功能选择'};
 const eventLabel=name=>labels[name]||({'工具:fix-blurry-pictures':'图片修复页','工具:ai-product-video-ads':'商品视频页','功能:ppt':'PPT页面'})[name]||name;
 const panels=[true,false].map(progressed=>{const x=samples.find(x=>x.progressed===progressed);if(!x)return `<div class="path-example"><h3>${progressed?'继续推进':'未到目标动作'}</h3><p class="muted">该需求暂未选出这一类代表样本。</p></div>`;
 const keyTimeline=x.timeline.filter(step=>step.event!=='login'&&!step.event.endsWith('_shown')&&!(step.event==='Studio'&&step.seconds_from_anchor>0));
 const visibleTimeline=keyTimeline.filter((step,i)=>i===0||step.event!==keyTimeline[i-1].event||step.event==='send_message');
 return `<div class="path-example"><div class="path-example-head"><h3>${progressed?'继续推进':'未到目标动作'}</h3><span class="scope-tag">${e(state.model.names[x.demand]||x.demand)}</span></div><ol class="path-timeline">${visibleTimeline.map(step=>`<li class="${step.seconds_from_anchor===0?'anchor-event':''}"><span class="path-time">${step.seconds_from_anchor<0?'−':'+'}${secs(Math.abs(step.seconds_from_anchor))}</span><span>${e(eventLabel(step.event))}</span></li>`).join('')}</ol><p class="path-outcome">${progressed?'样本达到该分岔的后续目标。':'30分钟内未记录到该分岔的后续目标。'}</p></div>`;
 }).join('');
 return `<article class="card"><div class="card-head"><div><h2>两类用户的代表路径</h2><p>${e(({entry_continue:"入口 → 继续浏览或操作",browse_use:"浏览 → 提交",signup_use:"注册 → 提交",attempt_continue:"首次提交 → 再次提交或付费意图",use_commercial:"首次提交 → 付费意图"})[branch]||"实际分岔")} · 时间相对此专题起点。</p></div>${scope('已选代表样本 · 按需求')}</div><div class="comparison-grid">${panels}</div><div class="note-row">轨迹保留关键动作，收起身份恢复、被动曝光与自动路由。节点率仍以全体合格访问计算；本专题样本不随日期、设备或状态重新抽取。</div></article>`;
}
function flowDetailsOnly(){const html=flowPanel();return '<article class="card">'+html.slice(html.indexOf('<div class="node-detail">'));}
function journey(){const axes=state.model.axis(state.filters);return `<div class="analysis-tabs tabs"><button data-journey-tab="map" class="${state.journeyTab==='map'?'active':''}">路径断点总览</button><button data-journey-tab="steps" class="${state.journeyTab==='steps'?'active':''}">逐步查看节点</button></div><div class="section-stack">${state.journeyTab==='map'?renderBreakpointMap(state.model,state.filters,state.node,state.breakpointDimension,state.breakpointExpanded)+flowDetailsOnly():flowPanel()}${representativePanel()}<div class="grid-two"><article class="card"><div class="card-head"><h2>每一步的推进与断点</h2>${scope('相同筛选 · 完整观察')}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>节点</th><th class="num">到达</th><th class="num">下一步率</th><th class="num">退出率</th></tr></thead><tbody>${axes.map(x=>`<tr><td><button class="table-link" data-node="${x.node}">${NODE_NAMES[x.node]}</button></td><td class="num">${num(x.arrived)}</td><td class="num">${pct(x.continue_rate)}</td><td class="num">${pct(x.exit_rate)}</td></tr>`).join('')}</tbody></table></div><div class="note-row">下一步与退出不是互补项，用户也可能走向其他操作。</div></article><article class="card"><div class="card-head"><h2>实际旅程保留分支</h2></div><div class="card-body"><div class="branch-route"><span class="route-step">落地</span>→<span class="route-step">注册</span>→<span class="route-step">原任务提交</span></div><div class="branch-route"><span class="route-step">落地</span>→<span class="route-step">尝试使用</span>→<span class="route-step">注册</span></div><div class="branch-route"><span class="route-step">认证</span>→<span class="route-step">回原工具</span>→<span class="route-step">结果 / 下载</span></div><div class="insight-box compact"><strong>重点核查原任务有没有被接住</strong><p>9/10前后，认证后返回原工具的路径增加。进入工具原页与进入工作台应按实际任务分别判断。</p></div><div class="action-row"><span class="plain-scope">代表性流程示意</span><button class="text-button blue" data-view="diagnosis">查看真实分岔对照 →</button></div></div></article></div></div>`;}
function dailyJourneyTable(days){
 const stages=state.dailyMode==='stages';
 const labels=stages?['入口 / 落地','浏览','注册','使用','注册后使用','当次复用','付费意图','结账','支付记录']:['入口后继续','浏览→注册/使用','注册→使用','使用→复用','复用→付费意图','支付后使用','入口退出率'];
 const metrics=['visits','browsed','registered','used','registered_use','reused','payment_intent','checkout','paid'];
 const nodes=['entry','browse','register','use','reuse','payment'];
 const rows=[...days].reverse().map(day=>{
  const columns=stages?metrics.map(key=>{const observed=['visits','browsed'].includes(key)||day.behavior_observed;return `<td class="num">${observed?num(day[key]):'—'}</td>`;}).join(''):
  nodes.map(node=>{const stat=day.journey[node];const observed=node==='entry'||day.behavior_observed;return `<td class="num">${observed?pct(stat?.rate??null):'—'}<small>${observed&&stat?.denominator?`${num(stat.continued)} / ${num(stat.denominator)}`:'无完整起点'}</small></td>`;}).join('')+`<td class="num">${pct(day.journey.entry?.exit_rate??null)}<small>${num(day.journey.entry?.exited||0)} 未见后续动作</small></td>`;
  return `<tr><td class="daily-date"><button class="table-link" data-filter-date="${day.date}">${day.date.slice(5).replace('-','/')}</button>${day.partial_day?'<small>部分日期</small>':''}</td>${columns}</tr>`;
 }).join('');
 return `<article class="card"><div class="card-head"><div><h2>按日查看完整用户流程</h2><p>从当天进入的访问出发，追踪各节点到达与有序推进。</p></div><div class="tabs"><button data-daily-mode="stages" class="${stages?'active':''}">阶段到达</button><button data-daily-mode="rates" class="${!stages?'active':''}">节点推进 / 退出</button></div></div><div class="table-wrap"><table class="data-table daily-journey-table"><thead><tr><th class="daily-date">入站日期</th>${labels.map(l=>`<th class="num">${l}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div><div class="note-row">${stages?'各列是独立到达人数，允许跳步与先用后注册；不能把相邻列直接相除当作转化率。':'率按每个节点后30分钟的完整观察计算；分子 / 分母在比例下方显示。'} 浏览来自页面或主动选择记录；8/17前注册/使用尚无完整覆盖。点击日期可进入当天的流程轴。</div></article>`;
}
function traffic(){const t=state.report.data.segments.trends;const jumps=(t.traffic_jumps||[]).filter(x=>x.increment>0).sort((a,b)=>b.increment-a.increment).slice(0,8);const days=state.model.daily(state.filters);const max=Math.max(...days.map(x=>x.visits),1);return kpis()+`<div class="section-stack">${trendPanel(285)}<article class="card"><div class="card-head"><div><h2>值得运营回查的增长日期</h2><p>同时看访问增量与后续使用，找到值得复制的动作。</p></div>${scope('全需求 · 全历史回查')}</div><div class="table-wrap"><table class="data-table"><thead><tr><th>日期</th><th class="num">入口访问</th><th class="num">较前日</th><th class="num">前日使用</th><th class="num">当日使用</th><th>下一步</th></tr></thead><tbody>${jumps.map(x=>{const earlier=x.previous||x.previous_summary||{};const before=t.days.find(d=>d.date===x.previous_date);return `<tr><td><button class="table-link" data-filter-date="${x.date}">${x.date.slice(5).replace('-','/')}</button></td><td class="num">${num(x.visits)}</td><td class="num"><span class="status-pill positive">+${num(x.increment)} · ${pct(x.relative_change)}</span></td><td class="num">${x.date<'2026-08-18'?'—':num(before?.used)}</td><td class="num">${x.date<'2026-08-18'?'尚无完整记录':num(x.current?.used)}</td><td>${x.date==='2026-08-23'?'回查有效放量操作':x.date>='2026-09-10'?'先核查新路径承接':'比较卡片与需求构成'}</td></tr>`;}).join('')}</tbody></table></div></article><div class="grid-two"><article class="card"><div class="card-head"><h2>9/10：使用链路变化</h2>${scope('固定时期专题')}</div><div class="card-body"><div class="insight-box"><strong>下降早于晚间新卡首见</strong><p>上午之后的入站人群已出现提交记录减少，新卡在晚间才陆续出现。优先回查当日工具、认证和任务采集变化。</p></div><div class="action-row"><span class="plain-scope">同入口、同素材比较</span><button class="text-button blue" data-view="diagnosis">查看分岔 →</button></div></div></article><article class="card"><div class="card-head"><h2>9/14：增长是否有效</h2>${scope('固定时期专题')}</div><div class="card-body"><div class="insight-box"><strong>新卡放量需要连到有效任务</strong><p>修复v2、去水印、视频编辑是该次增长的主要来源。回查卡片曝光与排序，同时验证认证后的原任务是否顺利开始。</p></div><div class="action-row"><span class="plain-scope">按需求查看新增流量</span><button class="text-button blue" data-filter-date="2026-09-14">查看当日流程 →</button></div></div></article></div>${dailyJourneyTable(days)}</div>`;}
function render(){if(!state.report)return;const oldFlowScroll=$('.flow-axis')?.scrollLeft??0;if(!VIEWS[state.view])state.view='overview';renderNav();$('#pageTitle').textContent=VIEWS[state.view][1];syncFilters();const makers={overview,demand:matrixView,journey,traffic};let html=makers[state.view]?.();if(html===undefined){const funcs={diagnosis:renderDiagnosis,retention:renderRetention,commercial:renderCommercial,opportunities:renderStrategy};const deepFuncs={diagnosis:(r,f)=>renderDeepDiagnosis(r,f,state.deepBranch),retention:(r,f)=>renderDeepRetention(r,f,state.deepDays),commercial:(r,f)=>renderDeepCommercial(r,f,state.deepMinutes)};const labels={diagnosis:['继续 vs 停止','认证与任务分岔'],retention:['回访后的使用对照','回访概览'],commercial:['复用到商业推进','价格与结果场景']};const tab=state.analysisTabs[state.view]||'overview';const controls=labels[state.view]?`<div class="analysis-tabs tabs"><button data-analysis-tab="deep" class="${tab==='deep'?'active':''}">${labels[state.view][0]}</button><button data-analysis-tab="overview" class="${tab==='overview'?'active':''}">${labels[state.view][1]}</button></div>`:'';const body=tab==='deep'&&deepFuncs[state.view]?(deepFuncs[state.view](state.report,state.filters)||'<div class="card"><div class="empty">深度比较将在本次数据重算后显示。</div></div>'):funcs[state.view](state.report,state.filters);html=controls+`<div class="insights-view section-stack">${body}</div>`;}if(makers[state.view]&&state.model.summary(state.filters).visits===0&&!(state.view==='demand'&&state.matrixMode==='account'))html=`<div class="card">${empty()}</div>`;$('#content').innerHTML=html;const flow=$('.flow-axis');if(flow){const active=flow.querySelector('.flow-node.active');flow.scrollLeft=state.centerNode&&active?Math.max(0,active.offsetLeft-flow.clientWidth/2+active.clientWidth/2):oldFlowScroll;state.centerNode=false;}$('#footerWindow').textContent=`观察起点 ${state.report.window.start.slice(0,10).replaceAll('-','/')} · 全部历史`;}
function readableTime(iso,full=false){return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',...(full?{second:'2-digit'}:{})}).format(new Date(iso));}
async function loadReport(){if(state.loading)return;state.loading=true;try{const resp=await fetch(CONFIG.reportUrl||'/api/report',{cache:'no-store'});if(!resp.ok)throw Error('report_unavailable');const report=await resp.json();const model=createModel(report);state.report=report;state.model=model;initFilters();render();refreshController.reportLoaded();}catch(err){if(!state.report){$('#content').innerHTML=`<div class="loading-card card"><h2>暂时无法读取分析数据</h2><p>请确认本机分析服务正在运行，随后重试。</p><button class="button spaced" data-action="retry">重新读取</button></div>`;}else toast('新数据暂时不可读，当前结果已保留。');console.error('Report loading failed:',err.message);}finally{state.loading=false;}}
function selectDate(date,apply=false){state.selectedDate=date;if(apply){state.filters.start=date;state.filters.end=date;$('#dateSelect').value='custom';$('#datePanel').hidden=true;syncFilters();navigate('journey');toast(`已筛选 ${date} 的入口访问`);}else{render();if(state.view==='traffic')$('#main').scrollIntoView({block:'start'});}}
document.addEventListener('click',event=>{const t=event.target.closest('button,a,[data-date]');if(!t)return;
 if(t.dataset.view){event.preventDefault();navigate(t.dataset.view);return;}
 if(t.closest('#nav')&&t.hash){event.preventDefault();navigate(t.hash.slice(1));return;}
 if(t.dataset.node){state.node=t.dataset.node;state.centerNode=true;render();return;}
 if(t.dataset.breakpointExpand){state.breakpointExpanded=!state.breakpointExpanded;render();return;}
 if(t.dataset.journeyTab){state.journeyTab=t.dataset.journeyTab;render();return;}
 if(t.dataset.breakdownDimension){state.filters[t.dataset.breakdownDimension]=t.dataset.breakdownValue;render();return;}
 if(t.dataset.analysisTab){state.analysisTabs[state.view]=t.dataset.analysisTab;render();return;}
 if(t.dataset.deepDays){state.deepDays=Number(t.dataset.deepDays);render();return;}
 if(t.dataset.deepMinutes){state.deepMinutes=Number(t.dataset.deepMinutes);render();return;}
 if(t.dataset.dailyMode){state.dailyMode=t.dataset.dailyMode;render();return;}
 if(t.dataset.metric){state.metric=t.dataset.metric;render();return;}
 if(t.dataset.matrixMode){state.matrixMode=t.dataset.matrixMode;render();return;}
 if(t.dataset.selectDemand){state.filters.demand=t.dataset.selectDemand;state.filters.maturity='all';syncFilters();render();return;}
 if(t.dataset.cellDemand){state.filters.demand=t.dataset.cellDemand;state.filters.maturity=t.dataset.cellStage;state.node=({registered_only:'register',used:'use',registered_used:'use',reused:'reuse',payment_intent:'reuse',checkout_started:'reuse',paid:'payment',paid_used:'payment'})[t.dataset.cellStage]||'entry';syncFilters();navigate('journey');return;}
 if(t.dataset.accountCell){state.filters.demand=t.dataset.accountCell;state.filters.maturity='all';syncFilters();navigate('retention');return;}
 if(t.dataset.clear){if(t.dataset.clear==='date'){state.filters.start=null;state.filters.end=null;$('#dateSelect').value='all';}else state.filters[t.dataset.clear]='all';syncFilters();render();return;}
 if(t.dataset.filterDate){selectDate(t.dataset.filterDate,true);return;}
 if(t.dataset.date||t.dataset.chartDate){selectDate(t.dataset.date||t.dataset.chartDate);return;}
 const action=t.dataset.action;if(action==='reset')resetFilters();if(action==='methods')$('#methodDialog').showModal();if(action==='retry')loadReport();
});
document.addEventListener('change',event=>{if(event.target.id==='deepBranchSelect'){state.deepBranch=event.target.value;render();}if(event.target.id==='breakpointDimension'){state.breakpointDimension=event.target.value;state.breakpointExpanded=false;render();}});
document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-date]')){event.preventDefault();selectDate(event.target.dataset.date);}if(event.key==='Escape')closeNav();});
$('#filterToggle').onclick=()=>{const open=$('#filterPanel').hidden;$('#filterPanel').hidden=!open;$('#filterToggle').setAttribute('aria-expanded',open);};
for(const [id,key] of Object.entries({demandSelect:'demand',maturitySelect:'maturity',deviceSelect:'device',browserSelect:'browser',sourceSelect:'source',entrySelect:'entry',countrySelect:'country',languageSelect:'language'}))$('#'+id).onchange=ev=>{state.filters[key]=ev.target.value;render();};
$('#dateSelect').onchange=ev=>{const value=ev.target.value;$('#datePanel').hidden=value!=='custom';state.selectedDate=null;if(value==='custom')return;if(value==='all'){state.filters.start=null;state.filters.end=null;}else if(value==='before'||value==='after'){state.filters.start=value==='before'?'2026-09-04':'2026-09-10';state.filters.end=value==='before'?'2026-09-09':'2026-09-15';}else{const end=new Date(cutoffDate()+'T12:00:00Z');end.setUTCDate(end.getUTCDate()-1);state.filters.end=end.toISOString().slice(0,10);end.setUTCDate(end.getUTCDate()-Number(value)+1);state.filters.start=end.toISOString().slice(0,10);}render();};
$('#applyDates').onclick=()=>{const start=$('#startDate').value,end=$('#endDate').value;if(!start||!end||start>end){toast('请填写有效的开始和结束日期。');return;}state.filters.start=start;state.filters.end=end;state.selectedDate=null;render();};
$('#resetFilters').onclick=resetFilters;
$('#navOpen').onclick=()=>{$('#sidebar').classList.add('open');$('#navScrim').hidden=false;};$('#navClose').onclick=closeNav;$('#navScrim').onclick=closeNav;$('#closeDialog').onclick=()=>$('#methodDialog').close();$('#methodDialog').addEventListener('click',ev=>{if(ev.target===$('#methodDialog'))$('#methodDialog').close();});window.addEventListener('hashchange',()=>{state.view=location.hash.slice(1)||'overview';render();});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(state.report)render();},180);});
renderNav();loadReport().then(()=>refreshController.start());
