import {escapeHTML as e,formatNumber as n,formatRate as pct,NODE_NAMES,DEVICES,BROWSERS} from './data.js';
export const COUNTRY_NAMES={IN:'印度',SG:'新加坡',US:'美国',CN:'中国',ID:'印度尼西亚',BR:'巴西',DE:'德国',PK:'巴基斯坦',JP:'日本',KR:'韩国',GB:'英国',TR:'土耳其',VN:'越南',PH:'菲律宾',MY:'马来西亚',FR:'法国',MX:'墨西哥',TH:'泰国',TW:'中国台湾',HK:'中国香港',CA:'加拿大',AU:'澳大利亚',RU:'俄罗斯',BD:'孟加拉国',NG:'尼日利亚',unknown:'未知地区'};
const DIMS={demand:'需求',entry:'入口',device:'设备',country:'国家 / 地区',language:'浏览器语言',browser:'浏览器'};
export function dimensionLabel(model,key,value){return (key==='demand'?model.names:key==='device'?DEVICES:key==='country'?COUNTRY_NAMES:key==='browser'?BROWSERS:{})[value]||value;}
export function renderBreakpointMap(model,filters,node='use',dimension='demand',expanded=false){
 const axes=model.axis(filters),display=axes.filter(x=>x.node!=='landing'),max=Math.max(...display.map(x=>x.denominator),1);const rows=model.breakpointGroups(filters,node,dimension);const ref=rows.find(x=>x.is_reference);const target=axes.find(x=>x.node===node);
 const map=`<article class="card"><div class="card-head"><div><h2>路径断点总览</h2><p>同时看未继续的规模与比例，再进入相近人群比较。</p></div><span class="scope-tag">同次访问 · 各节点后30分钟</span></div><div class="table-wrap"><div class="breakpoint-map">${display.map((x,i)=>`<button class="breakpoint-row ${x.node===node?'selected':''}" data-node="${x.node}"><span class="breakpoint-stem"><i>${i+1}</i></span><span class="breakpoint-label">${x.node==='entry'?'入口 / 落地':NODE_NAMES[x.node]}<small>到达 ${n(x.arrived)}${x.pending?` · ${n(x.pending)}待观察`:''}</small></span><span class="breakpoint-bar-space"><span class="breakpoint-stack" style="width:${100*x.denominator/max}%"><i style="width:${x.denominator?100*x.continued/x.denominator:0}%;background:#6c9fe9" title="指定下一步 ${n(x.continued)}"></i><i style="width:${x.denominator?100*x.other/x.denominator:0}%;background:#c0cee0" title="其他主动去向 ${n(x.other)}"></i><i style="width:${x.denominator?100*x.exit/x.denominator:0}%;background:#e8bebe" title="未见主动后续 ${n(x.exit)}"></i></span>${!x.denominator?'<em>暂无完整观察起点</em>':''}</span><span class="breakpoint-result">${n(x.exit)}<small>未继续 · ${pct(x.exit_rate)}</small></span></button>`).join('')}</div></div><div class="breakpoint-legend"><span><i style="background:#6c9fe9"></i>到指定下一步</span><span><i style="background:#c0cee0"></i>其他主动去向</span><span><i style="background:#e8bebe"></i>未见独立后续动作</span></div><div class="note-row">条长按完整观察起点的绝对规模绘制；颜色区分后续去向。高比例不是问题定论：可能是已完成、仅查阅、采集缺口或尚未再次使用。重复使用与回访的关系在“回访与复用”中继续比较。</div></article>`;
 const pp=v=>v==null?'—':`${v>0?'+':''}${(v*100).toFixed(1)} pp`;
 const breakdown=`<article class="card"><div class="card-head"><div><h2>${NODE_NAMES[node]}：差异集中在哪类人群</h2><p>当前节点 · ${n(target?.denominator||0)} 个完整观察起点</p></div><label class="breakpoint-dimension">展开维度<select id="breakpointDimension">${Object.entries(DIMS).map(([k,l])=>`<option value="${k}" ${k===dimension?'selected':''}>${l}</option>`).join('')}</select></label></div>${rows.length?`<div class="table-wrap"><table class="data-table breakpoint-group-table"><thead><tr><th>${DIMS[dimension]}</th><th class="num">到达起点</th><th class="num">继续主动操作</th><th class="num">未继续</th><th class="num">未继续率</th><th class="num">相近人群差异</th><th>反复出现的情况</th></tr></thead><tbody>${rows.slice(0,expanded?rows.length:8).map(x=>`<tr><td><button class="table-link" data-breakdown-dimension="${dimension}" data-breakdown-value="${e(x.key)}" title="${e(x.key)}">${e(dimensionLabel(model,dimension,x.key))}</button>${x.is_reference?'<small>本维度最多样本参照</small>':''}</td><td class="num">${n(x.n)}</td><td class="num">${n(x.continued)}</td><td class="num">${n(x.stopped)}</td><td class="num">${pct(x.stop_rate)}</td><td class="num">${x.is_reference?'参照':pp(x.adjusted_difference)}${x.common_strata?`<small>可比覆盖 ${pct(x.coverage)}</small>`:''}</td><td>${x.is_reference?'—':x.common_strata?`${x.same_direction_strata} / ${x.common_strata} 个细分格同方向`:'同类样本不足'}</td></tr>`).join('')}</tbody></table></div>${rows.length>8?`<div class="breakpoint-more"><span>共 ${rows.length} 组</span><button class="text-button" data-breakpoint-expand="1">${expanded?'收起到前8组':'展开全部分组'}</button></div>`:''}`:'<div class="empty">该节点当前没有可比较的人群。</div>'}<div class="note-row">参照：${ref?e(dimensionLabel(model,dimension,ref.key)):'无'}。“相近人群差异”控制其余的需求、入口、设备与进入周，在两组各至少5次访问的细分格内加权比较未继续率；不代表因果。点击分组可继续下钻。</div></article>`;
 return map+breakdown;
}
