/** Shared refresh controls. The server owns scheduling; tabs never run timers that start jobs. */
export function createRefreshController({getReport,onReportChange,toast,snapshot=false}){
 const $=s=>document.querySelector(s);let current=null,timer=null,stopped=false,pending=false,polling=false;
 const channel=!snapshot&&typeof BroadcastChannel!=='undefined'?new BroadcastChannel('meigen-refresh-settings'):null;
 if(channel)channel.onmessage=()=>poll();
 const when=s=>new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(s));
 const duration=s=>`${Math.floor((s||0)/60)} 分 ${Math.floor((s||0)%60)} 秒`;
 async function api(url,body){const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{method:body===undefined?'GET':'POST',cache:'no-store',signal:c.signal,headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok){const err=Error(data.error?.code||data.error||`http_${r.status}`);err.status=r.status;err.data=data;throw err;}return data;}finally{clearTimeout(t);}}
 function display(status){current=status;const job=status?.refresh||{},busy=['running','cancelling'].includes(job.state),cancelled=job.state==='cancelled',failed=job.state==='failed',enabled=status?.settings?.auto_enabled===true;
  const end=getReport()?.window?.end||status?.report?.window?.end;const source=status?.source_freshness;const latest=source?.state==='available'&&source.latest_event_at?source.latest_event_at:null;$('#dataCutoff').textContent=latest?`数据库最新事件 ${when(latest)} · 北京时间`:end?`报告窗口截至 ${when(end)} · 北京时间`:'等待首批数据';
  $('#autoRefresh').checked=enabled;$('#autoRefresh').disabled=snapshot||pending;$('#refreshButton').disabled=busy||snapshot;$('#refreshButton').classList.toggle('busy',busy);$('#refreshButton span').textContent=busy?'更新中…':'刷新数据';
  const cancel=$('#cancelRefresh');if(cancel){cancel.hidden=!busy;cancel.disabled=job.state==='cancelling';cancel.textContent=job.state==='cancelling'?'正在停止…':'取消本次';}
  const label=snapshot?'':busy?(job.state==='cancelling'?'正在取消更新':'本次更新中'):failed?'更新未完成':cancelled?'更新已取消':enabled?'自动更新已开启':'自动更新已关闭';
  $('#refreshState').className='status-label '+(busy?'updating':failed?'warning':'');$('#refreshState').innerHTML=`<i class="status-dot"></i><span></span>`;$('#refreshState span').textContent=label;
  $('#sidebarStatus').replaceChildren(document.createTextNode(label));if(!snapshot){const small=document.createElement('small');small.textContent='全部历史 · 北京时间';$('#sidebarStatus').append(small);}
  const banner=$('#statusBanner');banner.hidden=true;const details=$('#refreshProgress');if(details)details.hidden=!busy;
  if(busy){banner.hidden=false;banner.className='status-banner info';const prefix=!enabled?'自动更新已关闭，本次任务仍在执行。':'本次完成后间隔5分钟再自动更新。';const phase=job.phase_label||job.progress?.label||'准备数据';banner.textContent=`${prefix} ${phase}，已用 ${duration(job.elapsed_seconds)}。当前图表保留上一批结果。`;if(details){details.textContent=`${job.requested_cutoff?`本次更新目标 ${when(job.requested_cutoff)} · `:''}${job.trigger==='auto'?'自动任务':'手动任务'} · ${phase} · 已用 ${duration(job.elapsed_seconds)}${job.progress_updated_at?` · 最近进展 ${when(job.progress_updated_at)}`:''}`;}}
  else if(failed){banner.hidden=false;banner.className='status-banner';const codes={refresh_timeout:'本次运行超时',runner_failed:'数据读取或计算失败',cancel_timeout:'停止任务超时'};banner.textContent=`${codes[job.error?.code]||'本次更新未完成'}，仍展示截至 ${end?when(end):'上次成功'} 的结果。可以手动重试。`;}
  else if(cancelled){banner.hidden=false;banner.className='status-banner info';banner.textContent=`已取消本次更新，保留截至 ${end?when(end):'上次成功'} 的结果。`;}
 }
 async function poll(){if(stopped||snapshot||polling)return;polling=true;try{const status=await api('/api/status');display(status);if(status.report?.generation_id&&getReport()&&status.report.generation_id!==getReport().generation_id)await onReportChange();}catch{const banner=$('#statusBanner');banner.hidden=false;banner.className='status-banner';banner.textContent='暂时无法确认更新状态，当前已加载的数据仍然保留。';$('#refreshState').className='status-label warning';$('#refreshState').textContent='连接暂时中断';$('#refreshButton').disabled=false;$('#refreshButton').classList.remove('busy');$('#refreshButton span').textContent='刷新数据';}finally{polling=false;clearTimeout(timer);if(!stopped)timer=setTimeout(poll,['running','cancelling'].includes(current?.refresh?.state)?2500:5000);}}
 async function manual(){if(snapshot)return;try{const response=await api('/api/refresh',{trigger:'manual'});if(response.status)display(response.status);toast('已开始本次更新，可随时取消。');clearTimeout(timer);timer=setTimeout(poll,500);}catch(err){if(err.status===409){if(err.data.status)display(err.data.status);toast('已有更新任务正在运行，可查看进度或取消。');}else toast('暂时无法启动更新，上一批结果已保留。');}}
 async function setAuto(enabled){if(snapshot)return;pending=true;$('#autoRefresh').disabled=true;try{const response=await api('/api/settings',{auto_enabled:enabled});if(response.status)display(response.status);else await poll();channel?.postMessage({type:'settings_changed'});toast(enabled?'已开启共享自动更新；每次完成5分钟后再次更新。':'自动更新已关闭，所有标签页停止安排下一次更新。');}catch{toast('自动更新设置未保存，请重试。');if(current)display(current);}finally{pending=false;$('#autoRefresh').disabled=false;await poll();}}
 async function cancel(){if(snapshot)return;try{const response=await api('/api/refresh/cancel',{});if(response.status)display(response.status);toast('正在停止本次更新，上一批结果会保留。');clearTimeout(timer);timer=setTimeout(poll,500);}catch{toast('暂时无法取消，请稍后重试。');}}
 function start(){stopped=false;$('#refreshButton').onclick=manual;$('#autoRefresh').onchange=e=>setAuto(e.target.checked);if($('#cancelRefresh'))$('#cancelRefresh').onclick=cancel;if(snapshot){document.body.classList.add('snapshot-mode');display({settings:{auto_enabled:false},refresh:{state:'idle'}});$('.auto-refresh').hidden=true;$('#refreshButton').hidden=true;}else poll();}
 function stop(){stopped=true;clearTimeout(timer);}
 return {start,stop,poll,manual,cancel,setAuto,display,reportLoaded:()=>display(current)};
}
