const {chromium}=require('playwright');const assert=require('assert/strict'),fs=require('fs'),path=require('path');
(async()=>{
 const b=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined});
 const ctx=await b.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),p=await ctx.newPage();const errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:8876/#journey',{waitUntil:'networkidle'});await p.waitForSelector('.breakpoint-map');
 assert.match(await p.locator('#refreshState').innerText(),/自动更新已关闭/);assert.equal(await p.locator('#refreshButton').isDisabled(),false);checks.push('off_is_idle_not_false_updating');
 const report=await(await p.request.get('http://127.0.0.1:8876/api/report')).json();const {createModel}=await import('../report/data.js');const model=createModel(report),daily=model.daily({});for(const key of ['registered','used','registered_use','reused','checkout','paid','payment_intent'])assert.equal(daily.reduce((s,r)=>s+r[key],0),model.summary({})[key]);assert.equal(daily.reduce((s,r)=>s+r.browsed,0),model.axis({}).find(x=>x.node==='browse').arrived);checks.push('whole_journey_daily_conservation');
 await p.selectOption('#breakpointDimension','country');assert.match(await p.locator('.breakpoint-group-table').innerText(),/印度/);await p.locator('[data-breakdown-dimension="country"][data-breakdown-value="IN"]').click();assert.equal(await p.locator('#countrySelect').inputValue(),'IN');assert.match(await p.locator('#filterChips').innerText(),/印度/);checks.push('region_breakpoint_drilldown');await p.click('#resetFilters');
 await p.click('[data-journey-tab="steps"]');const edges=p.locator('.flow-connector');assert.equal(await edges.count(),6);const geom=await p.evaluate(()=>[...document.querySelectorAll('.flow-connector')].map(x=>{const r=x.getBoundingClientRect(),a=x.previousElementSibling.getBoundingClientRect(),bb=x.nextElementSibling.getBoundingClientRect();return r.left>=a.right-1&&r.right<=bb.left+1;}));assert(geom.every(Boolean));checks.push('six_connectors_between_nodes');
 await p.locator('#nav a[href="#demand"]').click();const header=p.locator('.matrix-table th').filter({hasText:'有注册信号，'});assert.equal(await header.locator('br').count(),1);checks.push('two_line_registration_header');
 await p.locator('#nav a[href="#traffic"]').click();const table=p.locator('.daily-journey-table');for(const text of ['浏览','注册','使用','当次复用','付费意图','结账','支付记录'])assert((await table.innerText()).includes(text));await p.click('[data-daily-mode="rates"]');assert.match(await table.innerText(),/注册→使用/);checks.push('daily_all_stages_and_rates');
 await p.locator('#nav a[href="#diagnosis"]').click();assert.match(await p.locator('#content').innerText(),/继续主动操作/);assert.match(await p.locator('#content').innerText(),/停止主动操作/);
 for(const key of ['entry_continue','browse_use','attempt_continue','use_register','signup_use','use_commercial']){await p.selectOption('#deepBranchSelect',key);const text=await p.locator('#content').innerText();assert(!/undefined|NaN/.test(text));assert(/前|起点|节点/.test(text));}
 checks.push('six_same_anchor_comparisons');
 await p.locator('#nav a[href="#retention"]').click();for(const x of ['未回访','回访但未再使用','回访并再次使用'])assert((await p.locator('#content').innerText()).includes(x));await p.click('[data-deep-days="14"]');assert.match(await p.locator('#content').innerText(),/之后14日/);checks.push('return_and_actual_reuse_three_groups');
 await p.locator('#nav a[href="#commercial"]').click();assert.match(await p.locator('#content').innerText(),/再次提交/);await p.click('[data-deep-minutes="2"]');assert.match(await p.locator('#content').innerText(),/前2分钟/);checks.push('repeat_to_commercial_landmark');
 // Multiple tabs use one authoritative setting. Turning it on does not start a task immediately.
 const p2=await ctx.newPage();await p2.goto('http://127.0.0.1:8876/',{waitUntil:'networkidle'});await p2.waitForSelector('.kpi-value');
 await p.locator('#autoRefresh').check();await p.waitForResponse(r=>r.url().endsWith('/api/settings')&&r.request().method()==='POST').catch(()=>{});
 let settings=await(await p.request.get('http://127.0.0.1:8876/api/settings')).json();assert.equal(settings.settings.auto_enabled,true);
 await p2.reload({waitUntil:'networkidle'});await p2.waitForFunction(()=>document.querySelector('#autoRefresh').checked);await p2.locator('#autoRefresh').uncheck();await p2.waitForFunction(()=>document.querySelector('#refreshState').textContent.includes('自动更新已关闭'));
 settings=await(await p.request.get('http://127.0.0.1:8876/api/settings')).json();assert.equal(settings.settings.auto_enabled,false);checks.push('shared_auto_switch_multiple_tabs');
 const old=await p.request.post('http://127.0.0.1:8876/api/refresh',{data:{}});assert.equal(old.status(),400);const blocked=await p.request.post('http://127.0.0.1:8876/api/refresh',{data:{trigger:'auto'}});assert.equal(blocked.status(),409);checks.push('old_tab_and_disabled_auto_cannot_start');
 const overs=[];
 for(const width of [1440,768,390]){await p.setViewportSize({width,height:960});for(const view of ['journey','demand','traffic','diagnosis','retention','commercial']){await p.goto('http://127.0.0.1:8876/#'+view,{waitUntil:'networkidle'});await p.waitForSelector('#content .card');if(await p.evaluate(()=>document.documentElement.scrollWidth)>width+1)overs.push({view,width});if(width!==768)await p.screenshot({path:path.join(__dirname,`revision-${view}-${width}.png`),fullPage:true,animations:'disabled'});}}
 assert.deepEqual(overs,[]);checks.push('responsive_views');assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(__dirname,'revision-results.json'),JSON.stringify({passed:true,checks,errors,overflow:overs,generation:report.generation_id},null,2));console.log(JSON.stringify({passed:true,checks}));await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
